# Generated by Django 2.2.10 on 2021-04-26 06:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseny',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'Baseny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cmentarze',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Cmentarze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Festiwale',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('Informacje', models.CharField(blank=True, max_length=254, null=True)),
                ('czas_trwania', models.CharField(blank=True, db_column='Czas trwania', max_length=254, null=True)),
                ('strona_internetowa', models.CharField(blank=True, db_column='Strona internetowa', max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Festiwale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kina',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('godzina_otwarcia', models.CharField(blank=True, max_length=100, null=True)),
                ('link_do_repertuaru', models.CharField(blank=True, db_column='link_do_repertuaru', max_length=200, null=True)),
                ('cena', models.CharField(blank=True, db_column='cena', max_length=300, null=True)),
                ('telefon', models.CharField(blank=True, db_column='telefon', max_length=20, null=True)),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Kina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kluby',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('strona_internetowa', models.CharField(blank=True, db_column='strona internetowa', max_length=200, null=True)),
                ('adres', models.CharField(blank=True, db_column='adres', max_length=150, null=True)),
                ('telefon', models.CharField(blank=True, db_column='telefon', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Kluby',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Muzea',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('godziny_otwarcia', models.CharField(blank=True, db_column='godziny otwarcia', max_length=100, null=True)),
                ('cena', models.CharField(blank=True, max_length=100, null=True)),
                ('adres', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Muzea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pomniki',
            fields=[
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, db_column='nazwa', max_length=254, null=True)),
                ('imie_i_nazwisko_autora', models.CharField(blank=True, db_column='imię i nazwisko autora', max_length=254, null=True)),
                ('typ', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Pomniki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Silownie',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('cena', models.CharField(blank=True, max_length=200, null=True)),
                ('godziny_otwarcia', models.CharField(blank=True, db_column='godziny otwarcia', max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('strona_internetowa', models.CharField(blank=True, db_column='strona internetowa', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Silownie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srodowisko',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Srodowisko',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teatry',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('adres', models.CharField(blank=True, db_column='adres', max_length=254, null=True)),
                ('cennik', models.CharField(blank=True, db_column='cennik', max_length=254, null=True)),
                ('strona_internetowa', models.CharField(blank=True, db_column='strona internetowa', max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('link_do_repertuaru', models.CharField(blank=True, db_column='link do repertuaru', max_length=254, null=True)),
                ('godziny_otwarcia', models.CharField(blank=True, db_column='godziny otwarcia', max_length=254, null=True)),
            ],
            options={
                'db_table': 'Teatry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zabytki',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('id_zabytek', models.BigIntegerField(blank=True, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('godziny_otwarcia', models.CharField(blank=True, max_length=100, null=True)),
                ('cena', models.CharField(blank=True, max_length=100, null=True)),
                ('adres', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('typ', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'Zabytki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propozycja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerokosc', models.CharField(max_length=100)),
                ('dlugosc', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=256)),
            ],
        ),
    ]
