# Generated by Django 2.2.10 on 2021-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropozycjePkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerokosc', models.CharField(max_length=100)),
                ('dlugosc', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=256)),
            ],
        ),
    ]
